apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sgula-site

resources:
  - namespace.yaml
  - postgres.yaml
  - api.yaml
  - routes.yaml

configMapGenerator:
  - name: sgula-admin-ui-overlay
    files:
      - admin.html=../public/admin.html
      - style.css=../public/style.css

generatorOptions:
  disableNameSuffixHash: true
